# Generated by Django 4.1 on 2023-11-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WRFoutFileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('path_file', models.FileField(blank=True, null=True, upload_to='wrfout_files/')),
                ('path_string', models.TextField(blank=True, null=True)),
                ('size', models.FloatField()),
            ],
        ),
    ]
