# Generated by Django 4.1 on 2023-10-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRFoutFileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('path', models.TextField()),
                ('size', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
