# Generated by Django 4.1 on 2023-11-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('diagnostic', models.CharField(max_length=100)),
                ('map_palet', models.CharField(blank=True, max_length=100, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, max_length=150, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('polygons', models.IntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('z', models.TextField()),
                ('x', models.TextField()),
                ('y', models.TextField()),
                ('min_x', models.FloatField()),
                ('max_x', models.FloatField()),
                ('min_y', models.FloatField()),
                ('max_y', models.FloatField()),
            ],
        ),
    ]
