# Generated by Django 4.1 on 2025-08-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diagnosticcache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosticCache',
        ),
    ]
