# Generated by Django 4.1 on 2025-08-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0002_auto_20231120_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('diagnostic', models.CharField(max_length=100)),
                ('map_palet', models.CharField(blank=True, max_length=100, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, max_length=150, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('polygons', models.IntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('z', models.TextField()),
                ('x', models.TextField()),
                ('y', models.TextField()),
                ('min_x', models.FloatField()),
                ('max_x', models.FloatField()),
                ('min_y', models.FloatField()),
                ('max_y', models.FloatField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
    ]
