# Generated by Django 4.1 on 2025-08-15 12:49

from django.db import migrations, models
import wrf_logic.models
from backend_django_tesis.helpers import populate_palettes

def populate_palettes_model(apps, schema_editor):
    populate_palettes()

class Migration(migrations.Migration):

    dependencies = [
        ('wrf_logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('map', 'Map'), ('3d_graphic', '3D Graphic')], max_length=20, validators=[wrf_logic.models.validate_type])),
            ],
        ),
        migrations.RunPython(populate_palettes_model)
    ]
