# Generated by Django 4.1 on 2023-10-21 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(max_length=50)),
                ('last_names', models.CharField(max_length=100)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isGuess', models.BooleanField(default=False)),
                ('isManager', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.TextField()),
                ('diagnostic', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('polygons', models.IntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
    ]
