# Generated by Django 4.1 on 2023-11-10 20:32

from django.db import migrations
from backend_django_tesis.helpers import populate_database


def populate_models(apps, schema_editor):
    populate_database()


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_models)
    ]
