# Generated by Django 4.1 on 2023-11-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20231120_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='date_time',
            field=models.DateTimeField(blank=True, max_length=150, null=True),
        ),
    ]
