# Generated by Django 4.1 on 2023-11-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='static/profile_images/'),
        ),
    ]
