# Generated by Django 4.1 on 2023-11-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20231110_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
