# Generated by Django 4.1 on 2023-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
