# Generated by Django 4.1 on 2023-11-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_diagnostic_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='maximum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='minimum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
