# Generated by Django 4.1 on 2023-11-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_diagnostic_maximum_diagnostic_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='map_palet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
