# Generated by Django 4.1 on 2023-11-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.TextField(blank=True)),
                ('server_space', models.FloatField(default=0)),
                ('icon', models.FileField(blank=True, null=True, upload_to='static/icons/')),
                ('icon_name', models.CharField(blank=True, max_length=200, null=True)),
                ('favicon', models.FileField(blank=True, null=True, upload_to='static/icons/')),
                ('favicon_name', models.CharField(blank=True, max_length=200, null=True)),
                ('home_top_image', models.FileField(blank=True, null=True, upload_to='static/images/')),
                ('home_top_image_name', models.CharField(blank=True, max_length=200, null=True)),
                ('card_diagnostics_image', models.FileField(blank=True, null=True, upload_to='static/images/')),
                ('card_diagnostics_image_name', models.CharField(blank=True, max_length=200, null=True)),
                ('card_my_diagnostics_image', models.FileField(blank=True, null=True, upload_to='static/images/')),
                ('card_my_diagnostics_image_name', models.CharField(blank=True, max_length=200, null=True)),
                ('home_content', models.TextField(blank=True)),
                ('card_diagnostics', models.TextField(blank=True)),
                ('card_my_diagnostics', models.TextField(blank=True)),
                ('help_content', models.TextField(blank=True)),
            ],
        ),
    ]
