# Generated by Django 4.1 on 2023-11-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.CharField(blank=True, max_length=3, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
