# Generated by Django 4.1 on 2023-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='home_text1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='home_text2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='help_content',
            field=models.TextField(blank=True),
        ),
    ]
