# Generated by Django 4.1 on 2023-11-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_content_home_text1_content_home_text2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='home_text1',
            new_name='card_diagnostics',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='home_text2',
            new_name='card_my_diagnostics',
        ),
        migrations.AddField(
            model_name='content',
            name='favicon',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='home_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='icon',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='site_title',
            field=models.TextField(blank=True),
        ),
    ]
