# Generated by Django 4.1 on 2023-11-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_home_text1_content_card_diagnostics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='server_space',
            field=models.FloatField(default=0),
        ),
    ]
