# Generated by Django 4.1 on 2023-11-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_content_server_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='card_diagnostics_image',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='card_my_diagnostics_image',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='home_top_image',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='static/icons/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='static/icons/'),
        ),
    ]
