# Generated by Django 4.1 on 2023-11-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_content_card_diagnostics_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='card_diagnostics_image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='card_my_diagnostics_image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='favicon_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='home_top_image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='icon_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
